name: Storybook Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook tests
        run: npm run build-storybook
      - name: serve Storybook tests
        run: npx http-server storybook-static --port 6006 
      - name: Build Storybook tests
        run: yarn test-storybook